    <footer>
        <div class="footer-content">
            <h3>Stay Connected</h3>
            <p>Email our company if you have any questions:</p>
            <a
                href="mailto:100225609@student.swin.edu.au?cc=104300597@student.swin.edu.au;104548805@student.swin.edu.au;104584362@student.swin.edu.au;104567729@student.swin.edu.au">
                Our company email
            </a>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2023 SKP. All Rights Reserved.</p>
        </div>
    </footer>