<input type="checkbox" id="navbar-checkbox">
        <!-- Checkbox for vertical nav in mobile view (enhancement) -->
        <label for="navbar-checkbox" class="navbar-button">
            <img src="images/hamburger-icon.png" alt="Hamburger Icon">
        </label>

        <img src="./images/SKPLogo.png" class="logo" alt="HOME">

        <div class="manage-link">
            <a href="login.php">
                MANAGE
            </a>
        </div>

        <!-- Standard nav bar -->
        <nav>
            <a href="index.php">
                <div> HOME </div>
            </a>
            <a href="jobs.php">
                <div> JOBS </div>
            </a>
            <a href="apply.php">
                <div> APPLY </div>
            </a>
            <a href="about.php">
                <div> ABOUT </div>
            </a>
            <a href="enhancements.php">
                <div> ENHANCEMENTS </div>
            </a>
        </nav>
